### PR TITLE
Autogen: Quartus

### LINKED ISSUE #12: Having only one register in a model results in a bug
When we only have one register in a Simulink model, our Avalon wrapper and tcl script get broken. 

In the Avalon wrapper autogen, I compute the upper index of the address via `ceil(log2(len(registers))) - 1`; when `len(registers) == 1`, this returns -1.

### LINKED ISSUE #15: Build kernel modules platform-independently
#7 and a7b6b48157236dc799a2b1ae46caf460d43d65e0 deal with just building the kernel module in general, which works on my Linux system. Most developers will be using Windows with a Linux VM, though, so the current solution won't work. 

If we really want this process automated, we need to come up with a way to build the kernel module on Windows as well. This could potentially be done in Quartus' embedded command shell.

### LINKED ISSUE #19: Remove fixed_num struct from driver code
The fixed_num struct
```c
struct fixed_num {
  int integer;
  int fraction;
  int fraction_len;
};
```
does not appear to be used anywhere, so there's no need for it to be in the device driver c files. 

According to the autogenerated comments, the struct is created in the `CreateMiscTopOfFile` method

### LINKED ISSUE #21: Put our Platform Designer components into a group
We can group our Platform Designer components into a group in the IP Catalog by putting something like `set_module_property GROUP "FPGA Open Speech Tools"` in the *_hw.tcl files.

We can automate this for the simulink model IP cores.

### LINKED ISSUE #24: Reduce system clock rate to make timing closure easier
As we currently implement them, the Simulink models only do computation for one system clock cycle (98.304 MHz) every 96 kHz. Students have been having problems meeting timing closure with some of the more complicated Simulink models. 

Since the Audio Mini isn't intended for super high-performance designs, we probably can get away with a much slower system clock than 98.304 MHz. Using a slower clock should make meeting timing closure somewhat easier.

### PR DESCRIPTION
**Pull request by fe-wickham**
# Quartus workflow

- Generate _hw.tcl component file
- Generate system.tcl file
- Generate system.qsys file using qsys-script
- Generate system using qsys-generate
- Generate project tcl file
- (Arria 10) Generate pll system using qsys-generate
- Generate project through making and running make_project.tcl
  - Also compiles project
- Convert .sof file to .rbf using quartus_cpf

# Running Autogen from the command line
Given that simulink_codegen/vhdl/autogen.m is on your Matlab path, run autogen to initiate the autogen process from the command line.

# Matlab Projects
Adds the Matlab project Simulink_codegen that allows the Matlab files in the project to be referenced by other projects (which automatically adds them to the Matlab path). More on this in my pull request in the Simulink Models repo.

# Make on Windows with WSL

Making kernel modules is now supported on Windows through the use of [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). In particular, the code now checks if it is a Windows system and then checks for WSL and attempts to make the kernel modules if WSL is found. Requiring WSL is particularly reasonable as Quartus 19.1 and above now uses WSL to function rather than using Cygwin.

Required installations:
- Windows Subsystem for Linux
- ` gcc, gcc-arm-linux-gnueabihf, libelf-dev` on WSL

# File structure
All new quartus workflow code is now located in `vhdl/quartus` and resources for the quartus workflow code are stored in `vhdl/quartus/res`. Currently I haven't touched the code that creates the tcl component but that could pretty reasonably be refactored into a create_tcl_component file and moved into `vhdl\quartus`.

## quartus_workflow.py
This file handles the logic of what should be executed for each stage. The entrypoint is `execute_quartus_workflow` that takes in the same InputStructure that is based on Matlab's json as well as takes in the working directory that all of this will be executed in. This file contains minimal logic on the contents of files that are generated, instead delegating that to  `quartus_template.py`

## quartus_template.py
As the name implies, this file is oriented around templates for quartus. This file handles the logic of what making the parts of a file that is generated by quartus_workflow. 

## target.py
This is a simple file that defines a namedtuple Target that contains all target specific information. The DE10 and Arria10 instances are created here and utilized in the previous files. This allows for easily adding new targets here as well as removing the need for if statements everywhere to change behavior based on the target system

# Additional Configuration of Simulink Projects
The only additional configuration needed for existing projects is this:  
`mp.target_system = "de10";`  
which configures the quartus generation to target the de-10. Alternatively,  
`mp.target_system = "arria10";`  
will configure it for the Arria 10 iWav SoM

Link to other pull requests:
[component_library PR](https://github.com/fpga-open-speech-tools/component_library/pull/4)
[simulink_models PR](https://github.com/fpga-open-speech-tools/simulink_models/pull/27)
Closes #12 
Closes #21 
Closes #15 
Closes #24 
Closes #19 
More updates coming

### CODE REVIEW

File: vhdl/generate_vhdl.m [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    catch
+    end
+end
+if exist('mp','var') == 0
+    sm_run_me_first;
+    %pause(3)
+end
+cmd = [bdroot,'([],[],[],''compile'');'];
+    try
+        eval(cmd)
```
Comment (fe-tdavis) [inline vhdl/generate_vhdl.m]: Is there an alternative to using the eval function here?  Could we simply call the bdroot command?

File: vhdl/quartus/res/DE10Nano_System.vhd [hunk 2]
```diff
@@ -0,0 +1,563 @@
...
+				-- -- HPS SPI connection to AD1939
+            -- hps_spim0_txd                       => AD1939_spi_CIN,                                                        
+            -- hps_spim0_rxd                       => AD1939_spi_COUT,                                                        
+            -- hps_spim0_ss_in_n                   => '1',                                                 
+            -- hps_spim0_ssi_oe_n                  => open,                                                  
+            -- hps_spim0_ss_0_n                    => HPS_spi_ss_n,                                                     
+            -- hps_spim0_ss_1_n                    => open,                                                     
+            -- hps_spim0_ss_2_n                    => open,                                                    
+            -- hps_spim0_ss_3_n                    => open,                                                     
+            -- hps_spim0_sclk_out_clk    				=> AD1939_spi_CCLK,
```
Comment (fe-tdavis) [inline vhdl/quartus/res/DE10Nano_System.vhd]: We need to uncomment these lines.  The change snuck in there a few months ago...

File: vhdl/quartus/res/DE10Nano_System.vhd [hunk 3]
```diff
@@ -0,0 +1,563 @@
...
+				
+				-- -- HPS I2C #1 connection to TPA6130
+				-- hps_i2c0_out_data                   => i2c_serial_sda_oe,           
+            -- hps_i2c0_sda                        => i2c_0_i2c_serial_sda_in,       
+            -- hps_i2c0_clk_clk                    => serial_scl_oe,               
+		      -- hps_i2c0_scl_in_clk                 => i2c_serial_scl_in,
```
Comment (fe-tdavis) [inline vhdl/quartus/res/DE10Nano_System.vhd]: Same with these

**Review by fe-tdavis — APPROVED** [review]
Overall looks good!  My only concern was the eval function in the Matlab function.  If possible, we should avoid using eval but if it's the cleanest way for that try-catch, we can go with it.

File: vhdl/generate_vhdl.m (hunk 1 above)
Comment (fe-wickham) [reply vhdl/generate_vhdl.m]: Yeah, I was definitely thinking there would be but there isn't that I can tell. The reason this is being done this way is the [bdroot](https://www.mathworks.com/help/simulink/slref/bdroot.html) command actually just returns model name as a string, and what is actually being run is the [model](https://www.mathworks.com/help/simulink/slref/model_cmd.html) command which requires the model name as the function name. So above for example it is really running `SE([],[],[],'compile')` when compiling the echo model.  

While SE() is more clear, that would require a small change for each model manually and remove the ability for the `generate_vhdl` file to be in a single location and work every time.

Comment (tvannoy) [reply vhdl/generate_vhdl.m]: I believe Ross uses `eval` as well in some of the simulink processing code.

**Comment by rksnider** [comment]
Yes.  The typical use case is a that a string needs to be constructed
dynamically that is then used in a command.

**Comment by rksnider** [comment]
The target configuration should be changed for the Arria 10 to specify the
specific board.  We already have two Arria 10 eval boards.  Maybe change
mp.target_system
to  mp.target_system.device and  mp.target_system.board  i.e.

DE10:
mp.target_system.device = Cyclone V
mp.target_system.board  = DE10-Nano

Audio Blade :
mp.target_system.device = Arria 10
mp.target_system.board  =  iWav SoM

**Comment by tvannoy** [comment]
Re: Simulink projects
---
Do all of those resources/*.xml files need to be committed, or are they autogenerated by the Simulink Project?

From my testing, it looks like the answer is they are required. I'm not sure how I feel about that. It's a lot of files that are pretty much empty. I'm not a big fan of having to track all of those files. If Matlab doesn't update those files every time the project is saved, that would be okay, but if they like to update them with nothing really changes (_cough_ Quartus project files _cough_), that will be really annoying. 

Having used Simulink projects now, what are your opinions on them? It seems like they would simplify path management, but I'm really not a fan of having an xml file for every file in the project. @rksnider should try using the Simulink projects to see what he thinks. 

Additionally, how does setting your Quartus path work with the Simulink projects? The HDL workflow advisor needs the path to your Quartus binary

We can defer the discussion/decision of whether to use Simulink projects until the full autogen codebase review next cycle.

**Comment by tvannoy** [comment]
> The target configuration should be changed for the Arria 10 to specify the
> specific board.  We already have two Arria 10 eval boards.  Maybe change
> mp.target_system
> to  mp.target_system.device and  mp.target_system.board  i.e.
> 
> DE10:
> mp.target_system.device = Cyclone V
> mp.target_system.board  = DE10-Nano
> 
> Audio Blade :
> mp.target_system.device = Arria 10
> mp.target_system.board  =  iWav SoM

I somewhat agree here. However, I think we should instead be referring to target devices by our hardware (e.g. audio mini, audio blade). I started using this convention in our AWS S3 buckets because I find it more meaningful for the end user than the specific COTS dev-board we are using. Our current naming convention is actually quite inconsistent, as we refer to all of the audio mini / Cyclone V projects as de10_nano or de10 (i.e. the dev board), while our Arria 10 projects are referred  to as arria10 (i.e. the fpga device family). Whatever we end up doing, we ought to be consistent everywhere.

**Comment by tvannoy** [comment]
# Compiling Drivers with WSL
I assume you've tested this? I have made kernel modules with WSL recently as I only had my Windows laptop with me ☹️, but I did run into some issues. 

For me, I couldn't put the kernel source tree in my Windows filesystem (where everything else, like the simulink_codegen repo, is) because NTFS isn't case sensitive. The kernel sources have files with the same names but differing case. This meant that I had to put the kernel sources in the WSL filesystem and change the path to the kernel source tree in the kernel module's Makefile. 

It looks like you are not generating different Makefiles for Windows and Linux. If this is working for you, maybe there is something I missed when compiling on my machine. 


**sidenote**: Quartus 19.1 uses WSL for the NIOS II Command Shell, but the 19.1 Embedded Design Suite still uses Cygwin. I don't know if they are planning on migrating EDS to use WSL too. Either way, I think requiring WSL to be installed is a perfectly reasonable dependency.

**Comment by rksnider** [comment]
Referring by hardware would be fine.  It was just the inconsistency that I
was having an issue with.

**Comment by tvannoy** [comment]
Is there a good project (e.g. the echo project) I can test all of this out on? I can get a better idea of the flow if I just run it myself and see how it works. It's difficult to tell what the generated files look like without running the code.

Is my understanding correct that the system.tcl file you create just adds the custom components into the base platform designer file? I remember perusing through the platform designer tcl documentation and seeing that functionality when I was investigating the device tree generation. That seems like the best way to do it.

**Comment by tvannoy** [comment]
Re: File Structure
---
I'm not necessarily a fan of moving the creation of the _hw.tcl for the IP core into the quartus subdir, as that _hw.tcl file is really tied to the IP core, not the quartus project. No need to worry about that in this PR, though, as we will address the organization of the autogen code base in the upcoming design review next cycle.

File: vhdl/autogen_quartus.py [hunk 4]
```diff
@@ -26,3 +32,11 @@ def write_tcl(input_struct, outputFilename):
...
         out_file.write(create_sink_connection_point(input_struct))
         out_file.write(create_source_connection_point(input_struct))
+
+def get_working_dir(dir):
+    if not(dir.endswith("\\")):
+        dir += "\\"
+    return dir + "quartus\\"
+        
+if __name__ == "__main__":
+    main('MNR_dataplane.json', "C:\\Users\\wickh\\Documents\\NIH\\simulink_models\\models\\short_window_mean_reduction\\hdlsrc\\MNR\\MNR_dataplane_avalon_hw.tcl", "C:\\Users\\wickh\\Documents\\NIH\\simulink_models\\models\\short_window_mean_reduction\\hdlsrc\\MNR")
```
Comment (tvannoy) [inline vhdl/autogen_quartus.py]: not a big deal right now, but when we start refactoring our code base, we should make this script a command-line executable as well, e.g. use `argparse` and follow the usual pattern:
```python
if __name__ == "__main__":
    args = parseargs()
    main(args)
```

File: vhdl/create_mm_connection_point.py [hunk 5]
```diff
@@ -28,7 +28,7 @@ def create_mm_connection_point(input_struct):
     built_string += "set_interface_property " + mmname + " CMSIS_SVD_VARIABLES \"\"\n"
     built_string += "set_interface_property " + mmname + " SVD_ADDRESS_GROUP \"\"\n\n"
 
-    built_string += "add_interface_port " + mmname + " " + mmname + "_address address Input " + str(input_struct.address_bus_size) + "\n"
+    built_string += "add_interface_port " + mmname + " " + mmname + "_address address Input " + str(input_struct.address_bus_size if input_struct.address_bus_size > 0 else 1) + "\n"
```
Comment (tvannoy) [inline vhdl/create_mm_connection_point.py]: thank you for fixing this bug 😄

File: vhdl/hdlworkflow.m [hunk 6]
```diff
@@ -3,9 +3,18 @@
 dataplane_name = 'dataplane';
 load_system(model);
 
+if mp.target_system == 'de10'
+    device_family = 'Cyclone V';
+    device = '5CSEBA6U23I7';
+elseif mp.target_system == 'arria10'
+    device_family = 'Arria 10';
+    device = '10AS066H2F34I1HG';
+end
```
Comment (tvannoy) [inline vhdl/hdlworkflow.m:12]: Do you know if the HDL workflow advisor requires the device and device family to be set? It would seem reasonable that we shouldn't need that information for the 'Generic ASIC/FPGA' workflow, but for some reason I think we might need them. If you don't know off the top of your head, this is worth looking into, as we could simplify the HDL workflow script if these parameters aren't needed.

File: vhdl/quartus/qsys_templates.py [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+        .replace("component_base_address", component_base_address) \
+        .replace("axi_master_name", target.axi_master_name) \
+        .replace("clock_name", target.clock_name)
+        
+        if(self.custom_components_added == 0):
+            built_string += qsys_templates.custom_component_header
+            built_string += custom_component_initial_audio_in_connection_template.replace("component_name", component_name).replace("audio_in", target.audio_in)
+        if((self.custom_components_added + 1) == self.num_custom_components):
+            built_string += custom_component_final_audio_out_connection_template.replace("component_name", component_name).replace("audio_out", target.audio_out)
+            self.custom_components_added = 0
```
Comment (tvannoy) [inline vhdl/quartus/qsys_templates.py]: Does this mean that we can add a chain of custom components, e.g. codec -> echo -> gain -> compression -> codec? If so, how does that work?

File: vhdl/generate_vhdl.m (hunk 1 above)
Comment (fe-tdavis) [reply vhdl/generate_vhdl.m]: Gotcha.  Just wanted to make sure we weren't using it unnecessarily since it's generally a better practice not to use eval b/c it can make the code difficult to read and can be less efficient.

File: vhdl/quartus/quartus_workflow.py [hunk 8]
```diff
@@ -0,0 +1,263 @@
...
+    working_dir : string
+        Working directory of the generation process
+    """
+    log_msg = "Generating and compiling project"
+    cmd = f"cd {working_dir} & quartus_sh -t make_project.tcl"
+    log_file_path = working_dir + "project_gen.log"
+    
+    run_cmd_and_log(cmd, log_msg, log_file_path)
+
+def gen_rbf(working_dir, target_system):
```
Comment (tvannoy) [inline vhdl/quartus/quartus_workflow.py:284]: I'd prefer to hook the rbf generation into the quartus project itself as a post-compile hook, then we always get an rbf every time we compile a project, even if we aren't using this autogen script. We are planning on doing the same with the device tree overlays. 

We can worry about that decision during the full autogen code review

**Comment by tvannoy** [comment]
If we make a small change to a Simulink model, do we blast out the old Quartus project and create an entirely new one? That's the easiest thing to do, but I wonder if we could save quite a bit of time by recognizing that a project already exists and just updating it.

File: vhdl/quartus/res/components.ipx [hunk 9]
```diff
@@ -0,0 +1,14 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (tvannoy) [inline vhdl/quartus/res/components.ipx:1]: Just looking forward to the full autogen design review here: 
could we put the ipx file in a common folder that's shared between all Quartus projects, whether they were autogened or not? E.g.
```
de10_nano_projects
|
|---common
     |--- components.ipx
|--- project1
|--- project2
...
```

File: vhdl/quartus/target.py [hunk 10]
```diff
@@ -0,0 +1,21 @@
...
+    top_level_vhdl_file='DE10Nano_System.vhd', original_system='soc_system', base_address='20', axi_master_name='hps.h2f_lw_axi_master', \
+    audio_in='FE_Qsys_AD1939_Audio_Mini_v1_0.Line_In', audio_out='FE_Qsys_AD1939_Audio_Mini_v1_0.Headphone_Out', \
+    clock_name='clk_hps'    
+    )
+Arria10 = Target(name='arria10', system_name='arria10_system', device_family='Arria 10', \
+    device='10AS066H2F34I1HG', base_qsys_file='som_system.qsys', base_proj_tcl_file='arria10_proj.tcl', \
+    files_list=['A10SoM_System.vhd', 'arria10_system/arria10_system.qip', 'pll.qsys'], \
+    top_level_vhdl_file= 'A10SoM_System.vhd', original_system='som_system', base_address='20', \
+    axi_master_name='arria10_hps_0.h2f_lw_axi_master', audio_in='FE_Qsys_AD1939_Audio_Research_v1_0.Line_In', \
+    audio_out='FE_Qsys_AD1939_Audio_Research_v1_0.Headphone_Out', clock_name='clk_1'
```
Comment (tvannoy) [inline vhdl/quartus/target.py]: I would format these according to PEP 8. I don't believe we need the `\` chars for continuation, as `()` works as a continuation scope. 

We should run autopep8 on our python code as a matter of habit, though sometimes it formats things a little weird so I do change formatting occasionally.

File: vhdl/vgenAvalonWrapper.py [hunk 11]
```diff
@@ -75,8 +75,10 @@ def create_entity(name, sink_enabled, sink, source_enabled, source,
 
     # avalon memorymapped bus
     if registers_enabled:
+        num_of_registers = int(ceil(log(len(registers),2)) - 1)
+        num_of_registers =  num_of_registers if num_of_registers >= 0 else 0
         entity += indent*2 + "avalon_slave_address".ljust(26, ' ') + ": in  std_logic_vector({} downto 0);\
-            \n".format(str(int(ceil(log(len(registers),2)) - 1)).ljust(3, ' '))
+            \n".format(str(num_of_registers).ljust(3, ' '))
```
Comment (tvannoy) [inline vhdl/vgenAvalonWrapper.py]: was this to fix the bug in #12 ?

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (fe-tdavis) [reply vhdl/quartus/quartus_workflow.py:284]: It would probably be better to make that change now rather than later.  Don't want things to keep piling up. ;)

File: vhdl/vgenQuartus.m [hunk 12]
```diff
@@ -27,8 +27,13 @@
 % Bozeman, MT 59718
 % support@flatearthinc.com
 
-function vgenTcl(infile, outfile, additionalFilesetAbsDir)
+function vgenQuartus(infile, outfile, additionalFilesetAbsDir)
```
Comment (tvannoy) [inline vhdl/vgenQuartus.m]: I don't agree with lumping the _hw.tcl file for the IP core in the Quartus project generation. I assume that's what's going on here with the file name change. 

The IP core is conceptually separate from the Quartus project, though of course we need the IP core _hw.tcl file to create the Quartus project. I think these should be separate operations. If anything, we should maybe have a program (with a command line version) that can generate the IP core (VHDL files and _hw.tcl file), rather than having them separate as they have been.

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (tvannoy) [reply vhdl/quartus/quartus_workflow.py:284]: Fair enough. We will want to make the rbf creation a post-compile hook for every project, so I didn't want to hold up this code review as it's more about simply creating a Quartus project. But I agree that if we have time, we might as well change it now, or at least start. I think the full codebase review will potentially have implications on how we organize our projects, post-compile hooks, etc., though, so I see some value in waiting to get that sorted before changing all of the Quartus projects. 

I also think getting the device tree generation stuff wrapped up this cycle is higher priority. Either way, good point ;)

**Review by tvannoy — CHANGES_REQUESTED** [review]

**Comment by fe-wickham** [comment]
> Is there a good project (e.g. the echo project) I can test all of this out on? I can get a better idea of the flow if I just run it myself and see how it works. It's difficult to tell what the generated files look like without running the code.  

The echo project is the only one I committed on the automation branch of simulink_models so it would be the easiest. Otherwise you can add `mp.target_system = "de10";` to the callback_init of any model, run the sm_run_me_first since there is no project and then generate_vhdl .

> Is my understanding correct that the system.tcl file you create just adds the custom components into the base platform designer file? I remember perusing through the platform designer tcl documentation and seeing that functionality when I was investigating the device tree generation. That seems like the best way to do it.

Your understanding sounds correct. I load in the pass-through qsys system, add the custom component, and then add the connections.

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (tvannoy) [reply vhdl/quartus/quartus_workflow.py:284]: I back off on my previous arguments a bit. Creating the post-compile hook here would be a matter of creating another tcl script and adding some lines to the *_proj.tcl files. That is separate from converting all of our existing projects to using the post-compile hook. 

So yes, if we all agree on using a post-compile hook instead, then let's do it here now 😉

File: vhdl/vgenAvalonWrapper.py (hunk 11 above)
Comment (fe-wickham) [reply vhdl/vgenAvalonWrapper.py]: Yes, it is. It does seem a bit inelegant though so I have refactored it to just: `max(int(ceil(log(len(registers),2)) - 1), 0)`

Comment (tvannoy) [reply vhdl/vgenAvalonWrapper.py]: ah, very nice. That's clean.

**Comment by tvannoy** [comment]
> 
> 
> > Is there a good project (e.g. the echo project) I can test all of this out on? I can get a better idea of the flow if I just run it myself and see how it works. It's difficult to tell what the generated files look like without running the code.
> 
> The echo project is the only one I committed on the automation branch of simulink_models so it would be the easiest. Otherwise you can add `mp.target_system = "de10";` to the callback_init of any model, run the sm_run_me_first since there is no project and then generate_vhdl .
> 
> > Is my understanding correct that the system.tcl file you create just adds the custom components into the base platform designer file? I remember perusing through the platform designer tcl documentation and seeing that functionality when I was investigating the device tree generation. That seems like the best way to do it.
> 
> Your understanding sounds correct. I load in the pass-through qsys system, add the custom component, and then add the connections.

Great, I'll check that out next week and give it a whirl. The architecture/flow all seems pretty reasonable to me so far. I'll be able to provide more feedback after I test things out.

File: vhdl/quartus/target.py (hunk 10 above)
Comment (fe-wickham) [reply vhdl/quartus/target.py]: Haven't heard of the autopep8 before, that made the fixing it pretty convenient

File: vhdl/autogen_quartus.py (hunk 4 above)
Comment (tvannoy) [reply vhdl/autogen_quartus.py]: by "not a big deal", I mostly mean I think it's more important to get the dtogen stuff in a "finished" state right now instead of doing this.

**Comment by fe-wickham** [comment]
> If we make a small change to a Simulink model, do we blast out the old Quartus project and create an entirely new one? That's the easiest thing to do, but I wonder if we could save quite a bit of time by recognizing that a project already exists and just updating it.

Everything is currently overwritten but it should be doable to reduce the full process down to just regenerating the system and recompiling the project.

**Comment by tvannoy** [comment]
> 
> 
> > If we make a small change to a Simulink model, do we blast out the old Quartus project and create an entirely new one? That's the easiest thing to do, but I wonder if we could save quite a bit of time by recognizing that a project already exists and just updating it.
> 
> Everything is currently overwritten but it should be doable to reduce the full process down to just regenerating the system and recompiling the project.

Seems like that would be worthwhile if it's not a lot of effort. I don't know that it would save much time overall, though, since the compilation process is really the time sink.

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (fe-tdavis) [reply vhdl/quartus/quartus_workflow.py:284]: Yeah, let's go ahead and do it.  I figured it would be pretty straightforward.  Even though it would fit in the review for the whole process, fixing it sooner rather than later would save time in the long run.

File: vhdl/autogen_quartus.py (hunk 4 above)
Comment (fe-tdavis) [reply vhdl/autogen_quartus.py]: I'm going to disagree with you here.  :)  I like the idea of using `argparse`, but we should also make this change now.  We should take the extra time now to design the code how we want it to run, then the final review should go more smoothly.

**Review by fe-tdavis — CHANGES_REQUESTED** [review]
Let's go ahead and add argument parsing with `argparse` to the autogen scripts

File: vhdl/autogen_quartus.py (hunk 4 above)
Comment (tvannoy) [reply vhdl/autogen_quartus.py]: Perfectly valid point :smile: 

Here are some examples of how we've used `argparse` elsewhere in our codebase:
- [combine_linker_configs.py](https://github.com/fpga-open-speech-tools/simulink_codegen/blob/master/ui/combine_linker_configs.py)
- [combine_ui_configs.py](https://github.com/fpga-open-speech-tools/simulink_codegen/blob/master/ui/combine_ui_configs.py)
- [gen_makefile.py](https://github.com/fpga-open-speech-tools/simulink_codegen/blob/master/device_drivers/gen_makefile.py)
- [awsdownloader.py](https://github.com/fpga-open-speech-tools/utils/blob/aws/runtime_config/awsdownloader.py)

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (tvannoy) [reply vhdl/quartus/quartus_workflow.py:284]: Here's some [documentation](https://www.intel.com/content/www/us/en/programmable/support/support-resources/design-examples/design-software/tcl/auto_processing.html) on adding tcl hooks into the compilation process. There are also some examples in our [Dropbox swap folder](https://www.dropbox.com/home/FlatEarth%20Team%20Folder/Swap/NIH/quartus%20autogen%20hooks/scripts)

File: vhdl/quartus/target.py (hunk 10 above)
Comment (tvannoy) [reply vhdl/quartus/target.py]: It's pretty nice. I'd be cool to setup code formatters for our entire codebase. Running autopep8 from vscode is a pleasure :grin:

File: vhdl/quartus/qsys_templates.py (hunk 7 above)
Comment (Penchant) [reply vhdl/quartus/qsys_templates.py]: That is what it means. I haven't actually done any upstream work to actually do such a thing, but all that needs to be done for this is adding the custom_component names in order to `input_struct.custom_components`. Currently I am just making an array out of the model name from the JSON.

Comment (tvannoy) [reply vhdl/quartus/qsys_templates.py]: Sweet. That'll be really cool. I suspect adding that into the simulink models themselves won't be worthwhile as we're targeting a single Simulink model scenario for end-users, but having that ability will be cool. I did something similar for combining multiple models into a unified GUI config file. For connecting multiple models, I think we could just take multiple dataplane json files as command-line input to this program. Then people have the option to run the tool manually to achieve the multiple model scenario. Or we could supply some sort of master config file that specifies tool/workflow options, such as combining multiple models, uploading the build files to AWS, etc.

**Comment by tvannoy** [comment]
@fe-wickham  Path separators were broken on Linux due to use of `\\`, so the quartus_workflow stuff wouldn't run. I've changed this in 986b2f0, but I have not tested on Windows yet. I've never had problems with path separator differences in Python scripts, but I may not have ever had a need to use explicit path separators in this code base yet. If 986b2f0 doesn't work, we will need to find a way to make these scripts OS-agnostic.

**Comment by tvannoy** [comment]
I got the quartus_workflow to run until it tried to generate the qsys system. It fails on running 
```bash
cd /mnt/data/trevor/research/NIH_SBIR_R44_DC015443/simulink_models/models/echo/hdlsrc/SE/quartus/ & qsys-script --script=de10_system.tcl --search-path="../../../../../component_library/**/*,$"
```

The qsys_script.log file reports 
```
2020.05.26.15:24:17 Error: File <b>de10_system.tcl</b> does not exist or is not accessible for read
```
It appears that the issue is that the `cd` command is not getting executed correctly, as when I manually navigate to the desired directory and run `qsys-script`, the program does succeed (sort of, it was taking a *really* long time to load the base system, so I aborted the process).

 Nice job on the error logging by the way! It's much better than the non-existent logging we had before. We could maybe improve our logging across the python codebase overall and use the `logging` module; I've used it in the past before and quite like it, though I don't know if it has any advantages for us here).

**Comment by tvannoy** [comment]
It looks like the workflow puts the quartus project in `<simulink model root>/hdlsrc/*/quartus`. Is that correct? I'm not sure what the preferred place to put the projects are. For our development purposes, I would probably put them in the quartus project repos, but that would not be the case for end-users. Perhaps we can make that a project configuration parameter. It would be slick if we could make configuration all graphical with Simulink projects; if we could that, I'd be more okay with having all of those Simulink project xml files.

**Comment by fe-wickham** [comment]
> It looks like the workflow puts the quartus project in `<simulink model root>/hdlsrc/*/quartus`. Is that correct? I'm not sure what the preferred place to put the projects are. For our development purposes, I would probably put them in the quartus project repos, but that would not be the case for end-users. Perhaps we can make that a project configuration parameter. It would be slick if we could make configuration all graphical with Simulink projects; if we could that, I'd be more okay with having all of those Simulink project xml files.

Currently that is the directory and it isn't quite as portable as the code may imply quite yet as the `working_dir` sets the location of this for everything but the search path for components is currently dependent on it being there. I should be able to get that changed though to figure out the relative path on the fly and use that as the search path.  

Currently that is also true of creating the _hw.tcl, it has the input for the filesets to be anywhere but if they aren't in the same directory it would fail since there is no path being included. The _hw.tcl files I feel like we could look at always putting in a generated autogen directory in the component_library, which would simplify things a bit since they already need that in their search path.

File: vhdl/quartus/res/DE10Nano_System.vhd (hunk 2 above)
Comment (fe-wickham) [reply vhdl/quartus/res/DE10Nano_System.vhd]: Done

File: vhdl/quartus/res/DE10Nano_System.vhd (hunk 3 above)
Comment (fe-wickham) [reply vhdl/quartus/res/DE10Nano_System.vhd]: Also done

File: vhdl/autogen_quartus.py (hunk 4 above)
Comment (fe-wickham) [reply vhdl/autogen_quartus.py]: Completed. Feel free to review the implementations. Creation of the Platform Designer component has been consolidated and moved to `create_hw_tcl.py` that is also available for use from the command line.

File: vhdl/hdlworkflow.m (hunk 6 above)
Comment (fe-wickham) [reply vhdl/hdlworkflow.m:12]: I don't although I wouldn't be surprised if it doesn't require it. I will look into it

File: vhdl/quartus/quartus_workflow.py (hunk 8 above)
Comment (fe-wickham) [reply vhdl/quartus/quartus_workflow.py:284]: Done. The current implementation, which exists in`res/gen_rbf.tcl`, loops through all sof files found in the output_files directory and converts them to rbf files. This keeps it flexible as it doesn't need to know the name of the sof file(s) to convert and isn't going to run into issues if there are multiple in the directory for whatever reason. It is also quick, so running it more than needed isn't a significant issue

File: vhdl/quartus/target.py (hunk 10 above)
Comment (fe-wickham) [reply vhdl/quartus/target.py]: Done

File: vhdl/vgenQuartus.m (hunk 12 above)
Comment (fe-wickham) [reply vhdl/vgenQuartus.m]: Separated out. I am not sure what you mean by this though:
> rather than having them separate as they have been.

**Comment by tvannoy** [comment]
> I got the quartus_workflow to run until it tried to generate the qsys system. It fails on running
> 
> ```shell
> cd /mnt/data/trevor/research/NIH_SBIR_R44_DC015443/simulink_models/models/echo/hdlsrc/SE/quartus/ & qsys-script --script=de10_system.tcl --search-path="../../../../../component_library/**/*,$"
> ```
> 
> The qsys_script.log file reports
> 
> ```
> 2020.05.26.15:24:17 Error: File <b>de10_system.tcl</b> does not exist or is not accessible for read
> ```
> 
> It appears that the issue is that the `cd` command is not getting executed correctly, as when I manually navigate to the desired directory and run `qsys-script`, the program does succeed (sort of, it was taking a _really_ long time to load the base system, so I aborted the process).
> 
> Nice job on the error logging by the way! It's much better than the non-existent logging we had before. We could maybe improve our logging across the python codebase overall and use the `logging` module; I've used it in the past before and quite like it, though I don't know if it has any advantages for us here).

The reason this wasn't working is that `&` launches the first command in the background, so the second command starts before the first has finished. Changing it to `&&` solves this problems as the second command only executes if the first command returns successfully with an exit code of 0.

File: vhdl/vgenQuartus.m (hunk 12 above)
Comment (tvannoy) [reply vhdl/vgenQuartus.m]: Sorry, I wasn't very clear there. The IP core is made up of all the .vhd files and the associated *_hw.tcl file. Currently, the .vhd files are generated by a program, and the _hw.tcl file is generated by a separate program. 

I was thinking it might be nice to have a wrapper program that generates both. For the Simulink workflow, doing so makes no difference at all. But for workflows that don't rely on Simulink, the wrapper program could be nice as it reduces one step. For non-Simulink workflows, users just need to create a dataplane.json file by hand and feed that into the vhdl/tcl/driver scripts to autogenerate code. 

Either way, combing the vhdl and _hw.tcl generation into one program is more a of conceptual consideration than a practical one.

**Comment by tvannoy** [comment]
> > It looks like the workflow puts the quartus project in `<simulink model root>/hdlsrc/*/quartus`. Is that correct? I'm not sure what the preferred place to put the projects are. For our development purposes, I would probably put them in the quartus project repos, but that would not be the case for end-users. Perhaps we can make that a project configuration parameter. It would be slick if we could make configuration all graphical with Simulink projects; if we could that, I'd be more okay with having all of those Simulink project xml files.
> 
> Currently that is the directory and it isn't quite as portable as the code may imply quite yet as the `working_dir` sets the location of this for everything but the search path for components is currently dependent on it being there. I should be able to get that changed though to figure out the relative path on the fly and use that as the search path.
> 
> Currently that is also true of creating the _hw.tcl, it has the input for the filesets to be anywhere but if they aren't in the same directory it would fail since there is no path being included. The _hw.tcl files I feel like we could look at always putting in a generated autogen directory in the component_library, which would simplify things a bit since they already need that in their search path.

Okay. I think we can discuss the directory organization and where to put things in more detail during the full autogen design review. 

If I recall correctly, we decided to make the path to the additional filesets in the _hw.tcl generation an absolute path to avoid relative path issues. This could certainly be relooked at.

**Comment by fe-wickham** [comment]
> Okay. I think we can discuss the directory organization and where to put things in more detail during the full autogen design review.  

Sounds good.
> If I recall correctly, we decided to make the path to the additional filesets in the _hw.tcl generation an absolute path to avoid relative path issues. This could certainly be relooked at.

The issue I am referencing I think might be more clear with this an example I just ran: 
 `create_hw_tcl.py -j "SE_dataplane.json"  -o "C:\Users\wickh\Documents\NIH\simulink_models\models\echo\SE_dataplane_avalon_hw.tcl"
-w "C:\Users\wickh\Documents\NIH\simulink_models\models\echo\hdlsrc\SE"`

The effect of this was it created a _hw.tcl identical to what it creates if I set the output filepath  `echo\hdlsrc\SE` like it normally is, which means it created a tcl file with no valid filepath to the filesets. After thinking about it, I don't think we should actually do relative paths for that as it is just messy to have the filesets separate from the tcl file, however I think we should prevent them being separated by the generator like I did above. One option is to copy the filesets to what ever directory the .tcl file is placed into.

**Comment by tvannoy** [comment]
> > Okay. I think we can discuss the directory organization and where to put things in more detail during the full autogen design review.
> 
> Sounds good.
> 
> > If I recall correctly, we decided to make the path to the additional filesets in the _hw.tcl generation an absolute path to avoid relative path issues. This could certainly be relooked at.
> 
> The issue I am referencing I think might be more clear with this an example I just ran:
> `create_hw_tcl.py -j "SE_dataplane.json" -o "C:\Users\wickh\Documents\NIH\simulink_models\models\echo\SE_dataplane_avalon_hw.tcl" -w "C:\Users\wickh\Documents\NIH\simulink_models\models\echo\hdlsrc\SE"`
> 
> The effect of this was it created a _hw.tcl identical to what it creates if I set the output filepath `echo\hdlsrc\SE` like it normally is, which means it created a tcl file with no valid filepath to the filesets. After thinking about it, I don't think we should actually do relative paths for that as it is just messy to have the filesets separate from the tcl file, however I think we should prevent them being separated by the generator like I did above. One option is to copy the filesets to what ever directory the .tcl file is placed into.

Ah, okay. I see. Our convention has been to put the _hw.tcl file in the hdlsrc/SE/ directory where all of the vhdl files are. 

It's always been a little weird deciding where to place certain files. For instance, the json files are placed in the root of the simulink model folder, whereas all other generated files have been placed in hdlsrc/SE/. At one point I tried to place the generated VHDL files somewhere else, but the way I did it broke Simulink's code generation report, so I reverted back. 

I think figuring out where to place things warrants some more discussion. Our proejct/repo structure is fairly flat and sprawling... For example, we could have put the Simulink-generated code in the component_library where the rest of our components are, but we ended up deciding that maybe it made more sense to keep it with the model. 

While having all of the separate repos works fine for our development purposes, it's unlikely that we'll want to enforce that same directory structure on end-users who just want to create and deploy some Simulink models. I think we need a way to package things up for release and end-user scenarios.

File: vhdl/quartus/quartus_workflow.py [hunk 13]
```diff
@@ -0,0 +1,346 @@
...
+        raise ValueError(
+            f"The provided target: {config.target_system} is not supported")
+
+    abspath = os.path.abspath(__file__)
+    dname = os.path.dirname(abspath)
+    global RES_DIR
+    RES_DIR = os.path.dirname(abspath) + "/res/"
+    global QUARTUS_BIN_DIR
+    global QSYS_BIN_DIR
+    QUARTUS_BIN_DIR = os.environ["QSYS_ROOTDIR"].split("sopc_builder")[
```
Comment (tvannoy) [inline vhdl/quartus/quartus_workflow.py]: Is `QUARTUS_ROOTDIR_OVERRIDE` defined on your Windows system? If so, we can use that environment variable instead of having to split part of the `QSYS_ROOTDIR`

**Review by tvannoy — CHANGES_REQUESTED** [review]
The quartus workflow takes quite a while; it would be helpful to have some progress updates so we know that something is happening. 

It looks like this is attempted to some extent. After the quartus workflow is done, this shows up in MATLAB's command window:
```matlab
Column 1

    "Follow status in log files generated in "

  Column 2

    "/mnt/data/trevor/research/NIH_SBIR_R44_DC015443/s…"

Generating system
cd /mnt/data/trevor/research/NIH_SBIR_R44_DC015443/simulink_models/models/echo/hdlsrc/SE/quartus/ && /usr/local/intelFPGA/18.0/quartus/sopc_builder/bin/qsys-generate --synthesis=VHDL --search-path="../component_library/**/*,$"  de10_system.qsys
Generating make_project.tcl
Generating project
cd /mnt/data/trevor/research/NIH_SBIR_R44_DC015443/simulink_models/models/echo/hdlsrc/SE/quartus/ && /usr/local/intelFPGA/18.0/quartus/bin/quartus_sh -t make_project.tcl
Compiling project
cd /mnt/data/trevor/research/NIH_SBIR_R44_DC015443/simulink_models/models/echo/hdlsrc/SE/quartus/ && /usr/local/intelFPGA/18.0/quartus/bin/quartus_sh -t compile_project.tcl
```

On my system, the quartus workflow seems to block MATLAB.

File: vhdl/vgen_process_simulink_model.m [hunk 14]
```diff
@@ -105,12 +113,39 @@
...
+end
+
+if ispc
+    if system('wsl.exe cd') == 0 
+        system("wsl.exe dtc -@ -O dtb -o " + mp.target_system + ".dtbo " + mp.target_system + ".dts");
+    else
+        disp("Windows Subsystem for Linux is currently required to automate compiling device tree overlays")
+    end
+elseif isunix
+    system("dtc -@ -O dtb -o " + mp.target_system + ".dtbo " + mp.target_system + ".dts");
```
Comment (tvannoy) [inline vhdl/vgen_process_simulink_model.m:153]: I think the device tree overlay should have the same name as the quartus project, so `mp.model_name`

**Comment by tvannoy** [comment]
The whole autogen process works on Linux now, at least in the one test I've run.

**Comment by fe-wickham** [comment]
> The quartus workflow takes quite a while; it would be helpful to have some progress updates so we know that something is happening.

Beyond what you mentioned below, I am not sure what to do that makes sense, because I don't want to pretend it is making progress if it is hung due to Quartus not being licensed or some other issue.
> It looks like this is attempted to some extent. After the quartus workflow is done, this shows up in MATLAB's command window:

It looks like I didn't get an update to how Python runs committed. By adding this line:
```
pyenv("ExecutionMode", "OutOfProcess")
```
Python runs in a separate process and outputs to the command line as Python runs
> On my system, the quartus workflow seems to block MATLAB.

Unfortunately running Python out of process doesn't fix this issue. I have some things I want to investigate to deal with this issue, but I don't have anything that will clearly work at the moment.

File: vhdl/vgen_process_simulink_model.m (hunk 14 above)
Comment (fe-wickham) [reply vhdl/vgen_process_simulink_model.m:153]: The sof file is named based on the project revision (by Quartus) and because I support both de-10 and audioblade based on project revisions the project revision isn't the project name. I could look at renaming project revisions to something like "echo_de10" to still support either target but make the rbf file have a more descriptive name than it currently does.

File: vhdl/quartus/quartus_workflow.py (hunk 13 above)
Comment (fe-wickham) [reply vhdl/quartus/quartus_workflow.py]: It isn't, although I do have `QUARTUS_ROOTDIR`. I avoided using it because my Quartus installation on Linux only made `QSYS_ROOTDIR` available. Using `QSYS_ROOTDIR` entirely enables it to be consistent across Linux and Windows.

**Comment by tvannoy** [comment]
> Python runs in a separate process and outputs to the command line as Python runs

By this do you mean that the output of the quartus commands show up in MATLAB's command window? If that's the case, that's the behavior that I want. MATLAB's HDL Coder (and maybe other toolboxes) redirect Quartus' output to command window. 

>Unfortunately running Python out of process doesn't fix this issue. I have some things I want to investigate to deal with this issue, but I don't have anything that will clearly work at the moment.

I feel like having the MATLAB GUI blocked isn't too big of a deal as long as we can tell that something is happening.

File: vhdl/vgen_process_simulink_model.m (hunk 14 above)
Comment (tvannoy) [reply vhdl/vgen_process_simulink_model.m:153]: Ah, okay. That makes sense. It's a shame that Quartus hard codes the sof file based on the project revision name. 

I'm in favor of having project revisions have the form `<project_name>_<target_hardware>`. It's unfortunately a little bit redundant, but having more descriptive rbf and dtbo names will be helpful. Having the rbf just be de10/auiodblade wouldn't ruin the AWS overlay installation, but I think having the files contain the project name will in general be helpful when dealing with multiple projects.

File: vhdl/quartus/quartus_workflow.py (hunk 13 above)
Comment (tvannoy) [reply vhdl/quartus/quartus_workflow.py]: Okay, I must have defined `QUARTUS_ROOTDIR_OVERRIDE` manually on my Linux install. 

I think using the environment variables is a fine choice, but it can lead to confusion when there are multiple Quartus installations on a machine. By using the environment variables, the Quartus path that we specify for MATLAB doesn't necessarily reflect the path that is in the environment variable. This was the case on my machine, as I have both 18.0 and 19.1 installed. 

I'm not opposed to using the environment variable, but I wonder if we could use the environment variables in MATLAB as well. That would eliminate one path setup step. This comes at the cost of less flexibility in choosing which Quartus install to use.

**Review by tvannoy — APPROVED** [review]

**Comment by tvannoy** [comment]
I merged so we can do our full system review. There are only a few outstanding changes/suggestions here, and we can address them in the full review.
